artifact_uri: /Users/nicholaspate/Documents/01_Active/ATLAS/backend/ATLAS_Enhanced/963457480209310005/ca5eddfbf5964ef7b08a29560ef3dec4/artifacts
end_time: 1759013910654
entry_point_name: ''
experiment_id: '963457480209310005'
lifecycle_stage: active
run_id: ca5eddfbf5964ef7b08a29560ef3dec4
run_name: chat_6f1d7d2f
source_name: ''
source_type: 4
source_version: ''
start_time: 1759013910646
status: 3
tags: []
user_id: nicholaspate
