artifact_location: /Users/nicholaspate/Documents/01_Active/ATLAS/backend/ATLAS_Enhanced/0
creation_time: 1759004234796
experiment_id: '0'
last_update_time: 1759004234796
lifecycle_stage: active
name: Default
