artifact_uri: /Users/nicholaspate/Documents/01_Active/ATLAS/backend/ATLAS_Enhanced/374711745541914363/c64aed7c5ce24c118380a2bfba0efbc1/artifacts
end_time: 1759013942204
entry_point_name: ''
experiment_id: '374711745541914363'
lifecycle_stage: active
run_id: c64aed7c5ce24c118380a2bfba0efbc1
run_name: chat_7a48ae25
source_name: ''
source_type: 4
source_version: ''
start_time: 1759013942197
status: 3
tags: []
user_id: nicholaspate
