artifact_uri: /Users/nicholaspate/Documents/01_Active/ATLAS/backend/ATLAS_Enhanced/774459751002344962/88de4d6ddf2a45feaf6e96e506f10e1f/artifacts
end_time: 1759004533807
entry_point_name: ''
experiment_id: '774459751002344962'
lifecycle_stage: active
run_id: 88de4d6ddf2a45feaf6e96e506f10e1f
run_name: chat_672d7a37
source_name: ''
source_type: 4
source_version: ''
start_time: 1759004533799
status: 3
tags: []
user_id: nicholaspate
